const constants = {
  AD_PLAY: "AD_PLAY",
  CONTENT_CLICKED: "CONTENT_CLICKED",
  CONTENT_ENDED: "CONTENT_ENDED",
  CONTENT_PAUSE: "CONTENT_PAUSE",
  CONTENT_PLAY: "CONTENT_PLAY",
  DURATION_CHANGE: "DURATION_CHANGE",
  FULLSCREEN: "FULLSCREEN",
  NAME: "player",
  PAUSE: "PAUSE",
  PLAY: "PLAY",
  SETUP_NEW_PLAYER: "SETUP_NEW_PLAYER",
  SET_TIME: "SET_TIME",
  SET_VOLUME: "SET_VOLUME",
  MUTE: "MUTE",
  UNMUTE: "UNMUTE",
  SIZE_CHANGE: "SIZE_CHANGE",
  TIMEUPDATE: "TIMEUPDATE",
  VOLUME_BUTTON: "VOLUME_BUTTON"
};

export default constants;
